//#define HIHASH_IMPL
//#define HH_VALUE_TY
//#include <hihash.h>
#define HIMATH_IMPL
#include <himath.h>
#define HISTR_IMPL
#include <histr.h>
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>
#define CGLTF_IMPLEMENTATION
#include <cgltf.h>
#define TINYOBJ_LOADER_C_IMPLEMENTATION
#include <tinyobj_loader_c.h>
#define GLAD_VULKAN_IMPLEMENTATION
#include <glad/vulkan.h>