//#define HIHASH_IMPL
//#define HH_VALUE_TY
//#include <hihash.h>
#define HIMATH_IMPL
#include <himath.h>
#define HISTR_IMPL
#include <histr.h>
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>
#define CGLTF_IMPLEMENTATION
#include <cgltf.h>
#define TINYOBJ_LOADER_C_IMPLEMENTATION
#include <tinyobj_loader_c.h>
#ifdef _WIN32
#define GLAD_WGL_IMPLEMENTATION
#include <glad/wgl.h>
#endif //_WIN32
#define GLAD_GL_IMPLEMENTATION
#include <glad/gl.h>
